# Generated by Django 4.2.8 on 2023-12-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
