# Generated by Django 4.2.8 on 2023-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_actor_actor_movie_starring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starring',
            name='movie',
        ),
        migrations.AddField(
            model_name='starring',
            name='movie',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
