# Generated by Django 4.2.8 on 2023-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='starring',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
